version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: leaderboard-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: leaderboard
    volumes:
      - mongodb_data:/data/db
    networks:
      - leaderboard-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: leaderboard-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/leaderboard?authSource=admin
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - leaderboard-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: leaderboard-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - server
    networks:
      - leaderboard-network

volumes:
  mongodb_data:

networks:
  leaderboard-network:
    driver: bridge