services:
  - type: web
    name: leaderboard-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: leaderboard-frontend
    env: static
    buildCommand: cd frontend/leaderboard-app && npm install && npm run build
    staticPublishPath: ./frontend/leaderboard-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
